PlumTreeSystems\UserBundle\Entity\User:
    type: mappedSuperclass
    table: pts_user
    repositoryClass: PlumTreeSystems\UserBundle\Repository\UserRepository
    fields:
        email:
            type: string
            length: 191
            unique: true
        password:
            type: string
            length: 255
            nullable: true
        roles:
            type: string
            lenght: 255
        disabled:
            type: boolean
    lifecycleCallbacks: {  }
